### PR TITLE
Basic tests using asa_acl

### PR DESCRIPTION
**Pull request by ogenstad**
Tests using the asa_acl module.

### CODE REVIEW

**Comment by gundalow** [comment]
Yay for more tests. Had a quick look and it seems sensible (has idempotent tests in there) 

Wonder if there are any negative test cases we can add. I'll test in on our machines tomorrow and merge. Then look at what we can do to extend it.

**Comment by ogenstad** [comment]
I see this more as a start than a complete test. I heard about an issue in the networktocode group and I wanted to verify that the code didn't have those issues.

So yes additional tests should be added to this later on.

**Comment by gundalow** [comment]
@ogenstad This is a great addition, you've infinitely improved the coverage for the `asa_acl` module, so thanks for that.

My original comment was more me brain dumping ideas before I finished for the day.

**Comment by gundalow** [comment]
Turns out my asa machine are down at the moment, though I'll get this merged anyway

**Pull request merged**
