### PR TITLE
Purging dellosX_template modules

### PR DESCRIPTION
**Pull request by skg-net**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME
- modules/core/network/dellosX/dellosX_template
##### ANSIBLE VERSION
- ansible 2.2.0 (devel b427818f02) last updated 2016/09/30 11:17:30 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 537a7eb924) last updated 2016/09/30 11:17:43 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD a58e1d59c0) last updated 2016/09/30 11:17:43 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
##### SUMMARY
- Removing dellosX_template modules, since the functionality can be covered using dellosX_config module with src option.  Removing the corresponding test cases.

### CODE REVIEW

**Comment by skg-net** [comment]
@gundalow @privateip, please take a look at it.

**Comment by gundalow** [comment]
What I've done with the other template modules tests is:
`s/_template/_config/g`

And then copied the tests files (and `templates` directories) to the _config test directories.

**Comment by skg-net** [comment]
Will modify the test and add them to config tests, in a separate PR.

**Comment by gundalow** [comment]
@skg-net In that case I'll merge this PR and look forward to a fresh PR to defend the template functionality in `_config` modules

**Pull request merged**
